# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aabed35b94ecdec0f37bc553d520f05f1538d76867f01113abd8978b0c682347d836ea89fdadc72464b3040c99e32787759db0fe89b4e4aea933b9bfdacba459

test:
  secret_key_base: c1aa16c2fc2e9d26a2df26c4e4b0bd11cde627277681a220b6bc236385d0b2387112e02f5528060b209af19296d7f0cb9cb56a78b570d6ef09754081cbd90604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
